// Auto-generated metadata - do not edit manually
// Generated by scripts/generate-lab-metadata.ts

export interface LabEntryMetadata {
  slug: string;
  filePath: string;
  title: string;
  description: string | null;
  keywords: string[];
  thumbnail: string | null;
  ogImage: string | null;
  schemaType: string;
}

export const labMetadata: readonly LabEntryMetadata[] = [
  {
    "slug": "cargo-dispatch",
    "filePath": "cargo-dispatch.mdx",
    "title": "Cargo Dispatch",
    "description": "Programming game for routing packages from warehouse shelves to delivery trucks",
    "keywords": [
      "development",
      "programming",
      "coding",
      "typescript",
      "javascript",
      "game",
      "programming game"
    ],
    "thumbnail": "/lab/cargo-dispatch.svg",
    "ogImage": "/lab/cargo-dispatch.og-image.png",
    "schemaType": "Game"
  },
  {
    "slug": "qr-code-generator",
    "filePath": "qr-code-generator.mdx",
    "title": "QR Code Generator",
    "description": "Design and download a styled QR code entirely in the browser, with center icons, frames, and custom colors",
    "keywords": [
      "qr code",
      "qr code generator",
      "qr",
      "barcode",
      "svg",
      "png",
      "wifi qr code",
      "vcard",
      "react",
      "typescript"
    ],
    "thumbnail": "/lab/qr-code-generator.svg",
    "ogImage": "/lab/qr-code-generator.og-image.png",
    "schemaType": "WebApplication"
  }
];
