// Auto-generated metadata - do not edit manually
// Generated by scripts/generate-lab-metadata.ts

export interface LabEntryMetadata {
  slug: string;
  filePath: string;
  title: string;
  description: string | null;
  keywords: string[];
  thumbnail: string | null;
  ogImage: string | null;
  schemaType: string;
}

export const labMetadata: readonly LabEntryMetadata[] = [
  {
    "slug": "cargo-dispatch",
    "filePath": "cargo-dispatch.mdx",
    "title": "Cargo Dispatch",
    "description": "Programming game for routing packages from warehouse shelves to delivery trucks",
    "keywords": [
      "development",
      "programming",
      "coding",
      "typescript",
      "javascript",
      "game",
      "programming game"
    ],
    "thumbnail": "/lab/cargo-dispatch.svg",
    "ogImage": "/lab/cargo-dispatch.og-image.png",
    "schemaType": "Game"
  },
  {
    "slug": "chart-builder",
    "filePath": "chart-builder.mdx",
    "title": "Chart Builder",
    "description": "A fully front-end AI agent that turns plain-language questions into real weather charts, with the system prompt and tools laid bare",
    "keywords": [
      "ai",
      "agent",
      "vercel ai sdk",
      "anthropic",
      "claude",
      "tools",
      "system prompt",
      "typescript",
      "data visualization"
    ],
    "thumbnail": "/lab/chart-builder.svg",
    "ogImage": "/lab/chart-builder.og-image.png",
    "schemaType": "WebApplication"
  }
];
