// Auto-generated metadata - do not edit manually
// Generated by scripts/generate-blog-metadata.ts

export interface BlogPostMetadata {
  slug: string;
  filePath: string;
  title: string;
  date: string;
  summary: string | null;
  image: string | null;
  thumbnail: string | null;
  note: string | null;
  tags: BlogTag[];
}

export type BlogTag = "data fetching" | "form management" | "graphics" | "javascript" | "node.js" | "react" | "ruby" | "ruby on rails" | "security" | "tanstack form" | "tanstack query" | "typescript" | "user experience";
