// Auto-generated metadata - do not edit manually
// Generated by scripts/generate-lab-metadata.ts

export interface LabEntryMetadata {
  slug: string;
  filePath: string;
  title: string;
  description: string | null;
  keywords: string[];
  thumbnail: string | null;
  ogImage: string | null;
  schemaType: string;
}
