// Auto-generated types - do not edit manually
// Generated by scripts/generate-blog-metadata.ts

export interface BlogPostMetadata {
  slug: string;
  filePath: string;
  title: string;
  date: string;
  summary: string | null;
  note: string | null;
  tags: string[];
}

export type BlogTag = "ruby" | "react" | "javascript" | "ruby on rails";
