// Auto-generated metadata - do not edit manually
// Generated by scripts/generate-blog-metadata.ts

export interface BlogPostMetadata {
  slug: string;
  filePath: string;
  title: string;
  date: string;
  summary: string | null;
  note: string | null;
  tags: BlogTag[];
}

export type BlogTag = "react" | "typescript" | "form management" | "javascript" | "ruby" | "ruby on rails";
