// Auto-generated metadata - do not edit manually
// Generated by scripts/generate-blog-metadata.ts

export interface BlogPostMetadata {
  slug: string;
  filePath: string;
  title: string;
  date: string;
  summary: string | null;
  image: string | null;
  thumbnail: string | null;
  note: string | null;
  tags: BlogTag[];
}

export type BlogTag = "ai" | "data fetching" | "form management" | "graphics" | "graphql" | "javascript" | "node.js" | "react" | "ruby" | "ruby on rails" | "security" | "tanstack form" | "tanstack query" | "typescript" | "user experience";

export const blogTags: ReadonlySet<BlogTag> = new Set([
  "ai",
  "data fetching",
  "form management",
  "graphics",
  "graphql",
  "javascript",
  "node.js",
  "react",
  "ruby",
  "ruby on rails",
  "security",
  "tanstack form",
  "tanstack query",
  "typescript",
  "user experience"
]);

export const blogMetadata: readonly BlogPostMetadata[] = [
  {
    "slug": "cooking-with-measurable",
    "filePath": "cooking-with-measurable.mdx",
    "title": "Cooking with measurable",
    "date": "2026-06-19",
    "summary": "I published measurable, a TypeScript library for converting between units of measurement. Here is a tour of what it does, built around four interactive recipe examples you can poke at: formatting labels, scaling servings, switching measurement systems, and merging recipes into one shopping list.",
    "image": "/blog/cooking-with-measurable.jpg",
    "thumbnail": "/blog/cooking-with-measurable.thumb.jpg",
    "note": null,
    "tags": [
      "typescript",
      "javascript",
      "react"
    ]
  },
  {
    "slug": "typing-graphql-across-client-and-server",
    "filePath": "typing-graphql-across-client-and-server.md",
    "title": "One Schema, Two Codegens: Typing GraphQL Across Client and Server",
    "date": "2026-06-17",
    "summary": "How I keep a single GraphQL schema as the source of truth across a client and a server: sharing the SDL, generating types on both ends, and using fragments to declare a shape once and compose it into complex reusable types.",
    "image": "/blog/typing-graphql-across-client-and-server.jpg",
    "thumbnail": "/blog/typing-graphql-across-client-and-server.thumb.jpg",
    "note": null,
    "tags": [
      "graphql",
      "node.js",
      "typescript",
      "javascript"
    ]
  },
  {
    "slug": "structuring-the-graphql-request-context",
    "filePath": "structuring-the-graphql-request-context.md",
    "title": "Structuring the GraphQL Request Context",
    "date": "2026-06-09",
    "summary": "My approach to shaping an Apollo server's GraphQL context around three fields: a resolved current user, a shared data layer, and a fresh set of DataLoaders.",
    "image": "/blog/structuring-the-graphql-request-context.jpg",
    "thumbnail": "/blog/structuring-the-graphql-request-context.thumb.jpg",
    "note": null,
    "tags": [
      "graphql",
      "node.js",
      "typescript",
      "javascript"
    ]
  },
  {
    "slug": "building-real-ai-agents-with-the-vercel-ai-sdk",
    "filePath": "building-real-ai-agents-with-the-vercel-ai-sdk.md",
    "title": "Building Real AI Agents with the Vercel AI SDK",
    "date": "2026-06-02",
    "summary": "The Vercel AI SDK makes it easy to call a model and stream a response, but the quickstart skips the parts that matter for a real application: forwarding the user's identity to your internal services, writing a system prompt that holds up under pressure, and building tools the model can't misuse. Here's how I approach all three.",
    "image": "/blog/building-real-ai-agents-with-the-vercel-ai-sdk.jpg",
    "thumbnail": "/blog/building-real-ai-agents-with-the-vercel-ai-sdk.thumb.jpg",
    "note": null,
    "tags": [
      "typescript",
      "node.js",
      "ai",
      "security"
    ]
  },
  {
    "slug": "fixing-tanstack-form-default-values-type-discrepancies",
    "filePath": "fixing-tanstack-form-default-values-type-discrepancies.md",
    "title": "Fixing TanStack Form `defaultValues` Type Discrepancies",
    "date": "2026-06-02",
    "summary": "When TanStack Form's `defaultValues` object narrows a union type to a more specific type than a given validation schema, TypeScript complains. However, there's a clean way to resolve it without sacrificing type safety.",
    "image": "/blog/fixing-tanstack-form-default-values-type-discrepancies.jpg",
    "thumbnail": "/blog/fixing-tanstack-form-default-values-type-discrepancies.thumb.jpg",
    "note": null,
    "tags": [
      "react",
      "typescript",
      "tanstack form",
      "form management"
    ]
  },
  {
    "slug": "reusing-form-sections-with-tanstack-forms-withfieldgroup",
    "filePath": "reusing-form-sections-with-tanstack-forms-withfieldgroup.md",
    "title": "Reusing Form Sections with TanStack Form's `withFieldGroup`",
    "date": "2026-05-31",
    "summary": "TanStack Form's `withFieldGroup` HOC is commonly shown being used with nested objects. Though it's not as well documented, it's also possible to extract reusable form sections from flat, non-nested data shapes.",
    "image": "/blog/reusing-form-sections-with-tanstack-forms-withfieldgroup.jpg",
    "thumbnail": "/blog/reusing-form-sections-with-tanstack-forms-withfieldgroup.thumb.jpg",
    "note": null,
    "tags": [
      "react",
      "typescript",
      "tanstack form",
      "form management"
    ]
  },
  {
    "slug": "building-a-predictive-text-input-in-react",
    "filePath": "building-a-predictive-text-input-in-react.md",
    "title": "Building a Predictive Text Input in React",
    "date": "2026-05-27",
    "summary": "Standard autocomplete dropdowns work well for simple cases, but sometimes you want inline \"ghost text\" predictions like an IDE. Here's how I built a predictive text input using contentEditable, careful cursor management, and a healthy respect for the DOM.",
    "image": "/blog/building-a-predictive-text-input-in-react.jpg",
    "thumbnail": "/blog/building-a-predictive-text-input-in-react.thumb.jpg",
    "note": null,
    "tags": [
      "react",
      "typescript",
      "form management",
      "user experience"
    ]
  },
  {
    "slug": "typescript-patterns-for-type-consistency",
    "filePath": "typescript-patterns-for-type-consistency.md",
    "title": "TypeScript Patterns for Type Consistency",
    "date": "2026-05-21",
    "summary": "Every TypeScript type you write is either earning its keep by catching drift, enforcing exhaustiveness, and surfacing mismatches between systems, or just decoration. Here are the patterns I reach for to keep types pulling their weight across a codebase.",
    "image": "/blog/typescript-patterns-for-type-consistency.jpg",
    "thumbnail": "/blog/typescript-patterns-for-type-consistency.thumb.jpg",
    "note": null,
    "tags": [
      "typescript"
    ]
  },
  {
    "slug": "orchestrating-image-to-svg-conversion-with-an-artifact-based-pipeline",
    "filePath": "orchestrating-image-to-svg-conversion-with-an-artifact-based-pipeline.md",
    "title": "Orchestrating Image-to-SVG Conversion with an Artifact-Based Pipeline",
    "date": "2026-03-20",
    "summary": "Converting raster images to vector graphics involves multiple processing stages, each feeding into the next. Here's how I designed an artifact-based pipeline architecture that tracks provenance, enforces type safety, and makes debugging complex transformations straightforward.",
    "image": "/blog/orchestrating-image-to-svg-conversion-with-an-artifact-based-pipeline.jpg",
    "thumbnail": "/blog/orchestrating-image-to-svg-conversion-with-an-artifact-based-pipeline.thumb.jpg",
    "note": null,
    "tags": [
      "typescript",
      "javascript",
      "graphics"
    ]
  },
  {
    "slug": "multi-step-form-validation-with-tanstack-form",
    "filePath": "multi-step-form-validation-with-tanstack-form.md",
    "title": "Multi-Step Form Validation with TanStack Form",
    "date": "2026-03-06",
    "summary": "There's a moment in every sufficiently complex form where a Zod schema isn't enough. The email is valid. The password meets requirements. And yet, there's still a bot check to run, an API to hit, an error to map back to the right field. Here's what that looks like in practice.",
    "image": "/blog/multi-step-form-validation-with-tanstack-form.jpg",
    "thumbnail": "/blog/multi-step-form-validation-with-tanstack-form.thumb.jpg",
    "note": null,
    "tags": [
      "react",
      "typescript",
      "tanstack form",
      "form management"
    ]
  },
  {
    "slug": "avoiding-tanstack-form-pitfalls",
    "filePath": "avoiding-tanstack-form-pitfalls.md",
    "title": "Avoiding TanStack Form Pitfalls",
    "date": "2026-01-08",
    "summary": "While integrating TanStack Form with schema validation libraries like Zod, I ran into a subtle type system gap that caused validation errors to silently fail. Here's how I diagnosed the issue and built a type-safe wrapper to prevent it from happening again.",
    "image": "/blog/avoiding-tanstack-form-pitfalls.jpg",
    "thumbnail": "/blog/avoiding-tanstack-form-pitfalls.thumb.jpg",
    "note": "After writing this article, I submitted a [pull request](https://github.com/TanStack/form/pull/1987) to TanStack Form that has since been merged, which resolves the pitfall covered in the first half of this article. Despite its acceptance into the codebase, the content in this article still provides beneficial insights related to types, generics, and ensuring a consistent error structure is used across forms.",
    "tags": [
      "react",
      "typescript",
      "tanstack form",
      "form management"
    ]
  },
  {
    "slug": "building-a-secure-javascript-sandbox-for-player-bot-scripts",
    "filePath": "building-a-secure-javascript-sandbox-for-player-bot-scripts.md",
    "title": "Building a Secure JavaScript Sandbox for Player Bot Scripts",
    "date": "2025-12-29",
    "summary": "How I built a secure sandbox for running untrusted player scripts using V8 isolates, a two-layer API architecture, and runtime code generation.",
    "image": "/blog/building-a-secure-javascript-sandbox-for-player-bot-scripts.jpg",
    "thumbnail": "/blog/building-a-secure-javascript-sandbox-for-player-bot-scripts.thumb.jpg",
    "note": null,
    "tags": [
      "typescript",
      "javascript",
      "node.js",
      "security"
    ]
  },
  {
    "slug": "deduplicating-parallel-queries-in-tanstack-query-react-query",
    "filePath": "deduplicating-parallel-queries-in-tanstack-query-react-query.md",
    "title": "Deduplicating Parallel Queries in TanStack Query (React Query)",
    "date": "2025-12-21",
    "summary": "When building time series charts that display percentages, you often need to fetch both numerator and denominator values for each data series. But what happens when multiple series share the same denominator? Here's how I used TanStack Query's `hashKey` function to deduplicate overlapping queries and map the results back to the original data structure.",
    "image": "/blog/deduplicating-parallel-queries-in-tanstack-query.jpg",
    "thumbnail": "/blog/deduplicating-parallel-queries-in-tanstack-query.thumb.jpg",
    "note": null,
    "tags": [
      "react",
      "typescript",
      "tanstack query",
      "data fetching"
    ]
  },
  {
    "slug": "building-a-reusable-form-component-library-with-tanstack-form",
    "filePath": "building-a-reusable-form-component-library-with-tanstack-form.md",
    "title": "Building a Reusable Form Component Library with TanStack Form",
    "date": "2025-12-18",
    "summary": "After years of working with react-hook-form, I made the switch to TanStack Form and built a reusable component library around it on top of my company's existing form components. Here are the patterns I landed on for binding these components to form state, creating intelligent buttons with automated loading states, and lazy-loading fields for better performance.",
    "image": "/blog/building-a-reusable-form-component-library-with-tanstack-form.jpg",
    "thumbnail": "/blog/building-a-reusable-form-component-library-with-tanstack-form.thumb.jpg",
    "note": null,
    "tags": [
      "react",
      "typescript",
      "tanstack form",
      "form management",
      "user experience"
    ]
  },
  {
    "slug": "pnpm-makes-monorepos-effortless",
    "filePath": "pnpm-makes-monorepos-effortless.md",
    "title": "pnpm Makes Monorepo Management Effortless",
    "date": "2025-09-15",
    "summary": "After years of struggling with challenges imposed by npm and yarn workspaces, pnpm demonstrates its ability to maintain monorepos effortlessly.",
    "image": "/blog/pnpm-makes-monorepos-effortless.jpg",
    "thumbnail": "/blog/pnpm-makes-monorepos-effortless.thumb.jpg",
    "note": null,
    "tags": [
      "javascript"
    ]
  },
  {
    "slug": "parsing-domain-names-now-in-gem-form",
    "filePath": "parsing-domain-names-now-in-gem-form.md",
    "title": "Parsing Domain Names - Now in Gem Form!",
    "date": "2015-01-02",
    "summary": "A feature for an internal Ruby project here at Quick Left necessitated parsing the domain from a URL. This seems like a problem for which there must already exist a solution, but it surprisingly turns out that there is no available solution for this seemingly simple task.",
    "image": null,
    "thumbnail": null,
    "note": "This article was originally published as part of the QuickLeft blog while employeed there. Given that the company has been acquired and the site no longer exists, I've rehosted the content here.",
    "tags": [
      "ruby"
    ]
  },
  {
    "slug": "april-fools-how-we-converted-our-site-to-doge-in-just-40-lines-of-code",
    "filePath": "april-fools-how-we-converted-our-site-to-doge-in-just-40-lines-of-code.md",
    "title": "April Fools! How We Converted Our Site to Doge in Just 40 Lines of Code",
    "date": "2014-04-01",
    "summary": "I recently wrote a blog post describing how to create your own RubyGem. The sample gem produced, aptly named dogeify, converts English sentences into \"Doge\" based upon the recently popular meme. For April Fools' Day, we thought it would be fun to implement this gem to convert our entire site into doge. Here's how we did it.",
    "image": null,
    "thumbnail": null,
    "note": "This article was originally published as part of the QuickLeft blog while employeed there. Given that the company has been acquired and the site no longer exists, I've rehosted the content here.",
    "tags": [
      "ruby",
      "ruby on rails"
    ]
  },
  {
    "slug": "step-by-step-guide-to-building-your-first-ruby-gem",
    "filePath": "step-by-step-guide-to-building-your-first-ruby-gem.md",
    "title": "Step-by-Step Guide to Building Your First Ruby Gem",
    "date": "2014-03-08",
    "summary": "Building your first Ruby gem may seem like a daunting task, but it's actually not so bad. It's quite rewarding to not only release a gem, but to see its download count climb as others put your hard work to good use, and even still as others offer to contribute new features and bug fixes to your very own gem. And thanks to RubyGems.org and Bundler, the process of creating, releasing, and implementing gems couldn't be easier.",
    "image": null,
    "thumbnail": null,
    "note": "This article was originally published as part of the QuickLeft blog while employeed there. Given that the company has been acquired and the site no longer exists, I've rehosted the content here.",
    "tags": [
      "ruby"
    ]
  },
  {
    "slug": "using-faux-activerecord-models-in-rails-3",
    "filePath": "using-faux-activerecord-models-in-rails-3.md",
    "title": "Using Faux ActiveRecord Models in Rails 3",
    "date": "2014-01-04",
    "summary": "Implementing forms that are associated with models -- specifically ActiveRecord objects -- is pretty common when developing with Ruby on Rails. In fact, the built-in FormHelper assumes that you're working with some kind of persisted object.\n\nBut what happens when you want to create a form for something that is not persisted by an ActiveRecord model?\n",
    "image": null,
    "thumbnail": null,
    "note": "This article was originally published as part of the QuickLeft blog while employeed there. Given that the company has been acquired and the site no longer exists, I've rehosted the content here.",
    "tags": [
      "ruby",
      "ruby on rails"
    ]
  }
];
