#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const __filename = path.basename(fileURLToPath(import.meta.url));
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, "..");
const contentDir = path.join(projectRoot, "src/content/lab");
const relativePath = path.join(path.relative(projectRoot, __dirname), __filename);

interface RawFrontmatter {
  title?: string;
  description?: string;
  published?: boolean;
  keywords?: string[];
  thumbnail?: string;
  ogImage?: string;
  schemaType?: string;
  [key: string]: unknown;
}

interface ProcessedLabEntry {
  slug: string;
  filePath: string;
  title: string;
  description: string | null;
  keywords: string[];
  thumbnail: string | null;
  ogImage: string | null;
  schemaType: string;
}

const autogeneratedComment = `// Auto-generated metadata - do not edit manually
// Generated by ${relativePath}`;

/**
 * Simple frontmatter parser that extracts YAML between --- delimiters
 */
function parseFrontmatter(content: string): RawFrontmatter | null {
  const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
  if (!frontmatterMatch) {
    return null;
  }

  try {
    return parseYaml(frontmatterMatch[1]) as RawFrontmatter;
  } catch (error) {
    console.error("Error parsing YAML frontmatter:", (error as Error).message);
    return null;
  }
}

/**
 * Extract frontmatter from all lab entries and generate metadata
 */
function generateLabMetadata(): void {
  console.log("🔍 Scanning for lab entries...");

  if (!fs.existsSync(contentDir)) {
    console.warn("⚠️  Lab content directory not found:", contentDir);
    return;
  }

  const entries: ProcessedLabEntry[] = [];
  const files = getAllMdxFiles(contentDir);

  console.log(`🧪 Found ${files.length} lab files`);

  for (const filePath of files) {
    try {
      const content = fs.readFileSync(filePath, "utf8");
      const frontmatter = parseFrontmatter(content);

      const relativePath = path.relative(contentDir, filePath);
      const slug = relativePath
        .replace(/\.(md|mdx)$/i, "")
        .replace(/\\/g, "/")
        .replace(/\/index$/, "");

      if (!frontmatter?.published) {
        continue;
      }

      if (!frontmatter?.title) {
        console.warn(`⚠️  Skipping ${relativePath}: missing title`);
        continue;
      }

      entries.push({
        slug,
        filePath: relativePath,
        title: frontmatter.title,
        description: frontmatter.description || null,
        keywords: frontmatter.keywords || [],
        thumbnail: frontmatter.thumbnail || null,
        ogImage: frontmatter.ogImage || null,
        schemaType: frontmatter.schemaType || "WebPage",
      });
    } catch (error) {
      console.error(`❌ Error processing ${filePath}:`, (error as Error).message);
    }
  }

  // Sort entries alphabetically by title
  entries.sort((a, b) => a.title.localeCompare(b.title));

  console.log(`✅ Processed ${entries.length} valid lab entries`);

  // Generate TypeScript metadata file
  const tsOutputPath = path.join(projectRoot, "src/data/lab-metadata.gen.ts");
  const outputDir = path.dirname(tsOutputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const tsContent = `${autogeneratedComment}

import type { LabEntryMetadata } from "@/types/lab.gen";

export const labMetadata: readonly LabEntryMetadata[] = ${JSON.stringify(entries, null, 2)};
`;

  fs.writeFileSync(tsOutputPath, tsContent);
  console.log(`📦 Generated metadata: ${tsOutputPath}`);

  // Generate TypeScript types
  generateTypes();
}

/**
 * Recursively find all MDX/MD files
 */
function getAllMdxFiles(dir: string): string[] {
  const files: string[] = [];
  const items = fs.readdirSync(dir);

  for (const item of items) {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      files.push(...getAllMdxFiles(fullPath));
    } else if (/\.(md|mdx)$/i.test(item)) {
      files.push(fullPath);
    }
  }

  return files;
}

/**
 * Generate TypeScript type definitions
 */
function generateTypes(): void {
  const typesPath = path.join(projectRoot, "src/types/lab.gen.ts");

  const typesDir = path.dirname(typesPath);
  if (!fs.existsSync(typesDir)) {
    fs.mkdirSync(typesDir, { recursive: true });
  }

  const typeDefinition = `${autogeneratedComment}

export interface LabEntryMetadata {
  slug: string;
  filePath: string;
  title: string;
  description: string | null;
  keywords: string[];
  thumbnail: string | null;
  ogImage: string | null;
  schemaType: string;
}
`;

  fs.writeFileSync(typesPath, typeDefinition);
  console.log(`🔧 Generated TypeScript types: ${typesPath}`);
}

// Run the script
generateLabMetadata();
