// Auto-generated metadata - do not edit manually
// Generated by scripts/generate-lab-metadata.ts

import type { LabEntryMetadata } from "@/types/lab.gen";

export const labMetadata: readonly LabEntryMetadata[] = [
  {
    "slug": "cargo-dispatch",
    "filePath": "cargo-dispatch.mdx",
    "title": "Cargo Dispatch",
    "description": "Programming game for routing packages from warehouse shelves to delivery trucks",
    "keywords": [
      "development",
      "programming",
      "coding",
      "typescript",
      "javascript",
      "game",
      "programming game"
    ],
    "thumbnail": "/lab/cargo-dispatch.svg",
    "ogImage": "/lab/cargo-dispatch.og-image.png",
    "schemaType": "Game"
  },
  {
    "slug": "space-explorer",
    "filePath": "space-explorer.mdx",
    "title": "Space Explorer",
    "description": "TODO",
    "keywords": [
      "development",
      "programming",
      "coding",
      "typescript",
      "javascript",
      "game",
      "space",
      "explorer",
      "exploration",
      "jetpack",
      "planets"
    ],
    "thumbnail": null,
    "ogImage": null,
    "schemaType": "Game"
  }
];
